# Generated by Django 2.2.19 on 2021-03-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terem',
            fields=[
                ('cim', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kapacitas', models.IntegerField(default=999)),
            ],
            options={
                'db_table': 'terem',
            },
        ),
    ]
