# Generated by Django 2.2.19 on 2021-04-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kepzes',
            fields=[
                ('kepzesid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nev', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'kepzes',
            },
        ),
    ]
