# Generated by Django 2.2.19 on 2021-03-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kurzus', '0002_auto_20210312_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idopont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kezdete', models.DateTimeField()),
                ('vege', models.DateTimeField()),
                ('kurzusKod', models.ForeignKey(db_column='kurzusKod', on_delete=django.db.models.deletion.CASCADE, to='kurzus.Kurzus')),
            ],
            options={
                'db_table': 'idopont',
                'unique_together': {('kezdete', 'vege', 'kurzusKod')},
            },
        ),
    ]
