# Generated by Django 2.2.19 on 2021-04-30 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_remove_hallgato_teljesitettkreditek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Befizetes',
            fields=[
                ('befizetesosszeg', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('datum', models.DateTimeField()),
                ('hallgatoAzonosito', models.OneToOneField(db_column='hallgatoAzonosito', on_delete=django.db.models.deletion.CASCADE, to='user.Hallgato')),
            ],
            options={
                'db_table': 'befizetes',
            },
        ),
    ]
