# Generated by Django 2.2.19 on 2021-04-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('befizetes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='befizetes',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='befizetes',
            name='befizetesosszeg',
            field=models.IntegerField(default=0),
        ),
    ]
