# Generated by Django 2.2.19 on 2021-05-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('befizetes', '0002_auto_20210430_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='befizetes',
            name='datum',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
