# Generated by Django 2.2.19 on 2021-03-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elofeltetel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elofeltetel',
            name='teljesitette',
        ),
    ]
