# Generated by Django 2.2.19 on 2021-03-11 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terem', '0001_initial'),
        ('user', '0002_etradmin_hallgato_oktato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurzus',
            fields=[
                ('kurzuskod', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('kurzusnev', models.CharField(max_length=64)),
                ('ferohely', models.IntegerField(default=999)),
                ('kredit', models.IntegerField(default=1)),
                ('oktatoAzonosito', models.OneToOneField(max_length=6, on_delete=django.db.models.deletion.CASCADE, to='user.Oktato')),
                ('teremCim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terem.Terem')),
            ],
            options={
                'db_table': 'kurzus',
            },
        ),
    ]
