# Generated by Django 2.2.19 on 2021-03-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurzus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurzus',
            name='oktatoAzonosito',
            field=models.OneToOneField(db_column='oktatoAzonosito', max_length=6, on_delete=django.db.models.deletion.CASCADE, to='user.Oktato'),
        ),
        migrations.AlterField(
            model_name='kurzus',
            name='teremCim',
            field=models.ForeignKey(db_column='teremCim', on_delete=django.db.models.deletion.CASCADE, to='terem.Terem'),
        ),
    ]
