# Generated by Django 2.2.19 on 2021-04-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurzus', '0005_auto_20210325_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurzus',
            name='meghirdetett',
            field=models.IntegerField(default=0),
        ),
    ]
