# Generated by Django 2.2.19 on 2021-03-13 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kurzus', '0002_auto_20210312_1131'),
        ('user', '0002_etradmin_hallgato_oktato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurzustfelvesz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teljesitette', models.IntegerField(default=0)),
                ('hallgatoAzonosito', models.ForeignKey(db_column='hallgatoAzonosito', on_delete=django.db.models.deletion.CASCADE, to='user.Hallgato')),
                ('kurzusKod', models.ForeignKey(db_column='kurzusKod', on_delete=django.db.models.deletion.CASCADE, to='kurzus.Kurzus')),
            ],
            options={
                'db_table': 'kurzustfelvesz',
            },
        ),
    ]
