# Generated by Django 2.2.19 on 2021-04-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurzustfelvesz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurzustfelvesz',
            name='evszam',
            field=models.IntegerField(default=0),
        ),
    ]
