# Generated by Django 3.2 on 2021-05-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzenet',
            fields=[
                ('id', models.AutoField(db_column='id', default=0, primary_key=True, serialize=False)),
                ('cim', models.CharField(max_length=20)),
                ('uzenet', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'uzenofal',
            },
        ),
    ]
