# Generated by Django 2.2.19 on 2021-05-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzenofal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzenet',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
