# Generated by Django 2.2.19 on 2021-03-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tartozas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tartozas',
            name='id',
        ),
        migrations.AlterField(
            model_name='tartozas',
            name='tartozasosszeg',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
