# Generated by Django 2.2.19 on 2021-03-24 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kurzus', '0003_auto_20210322_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vizsga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idopont', models.DateTimeField()),
                ('ferohely', models.IntegerField(default=999)),
                ('kurzusKod', models.ForeignKey(db_column='kurzusKod', on_delete=django.db.models.deletion.CASCADE, to='kurzus.Kurzus')),
            ],
            options={
                'db_table': 'vizsga',
                'unique_together': {('idopont', 'kurzusKod')},
            },
        ),
    ]
