# Generated by Django 2.2.19 on 2021-02-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EtrAdmin',
            fields=[
                ('azonosito', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('vezeteknev', models.CharField(max_length=64)),
                ('keresztnev', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('jelszo', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=None, to='user.User')),
            ],
            options={
                'db_table': 'etradmin',
            },
        ),
    ]
