# Generated by Django 2.2.19 on 2021-03-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtrAdmin',
            fields=[
                ('azonosito', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('vezeteknev', models.CharField(max_length=64)),
                ('keresztnev', models.CharField(max_length=64)),
                ('telefonszam', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('jelszo', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'etradmin',
            },
        ),
        migrations.CreateModel(
            name='Hallgato',
            fields=[
                ('azonosito', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('vezeteknev', models.CharField(max_length=64)),
                ('keresztnev', models.CharField(max_length=64)),
                ('szemelyiszam', models.CharField(max_length=64)),
                ('telefonszam', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('jelszo', models.CharField(max_length=64)),
                ('szulido', models.DateField()),
                ('teljesitettkreditek', models.IntegerField(default=0)),
                ('kepzes', models.CharField(default='Not_Defined', max_length=64)),
            ],
            options={
                'db_table': 'hallgato',
            },
        ),
        migrations.CreateModel(
            name='Oktato',
            fields=[
                ('azonosito', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('vezeteknev', models.CharField(max_length=64)),
                ('keresztnev', models.CharField(max_length=64)),
                ('szemelyiszam', models.CharField(max_length=64)),
                ('telefonszam', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('jelszo', models.CharField(max_length=64)),
                ('szulido', models.DateField()),
            ],
            options={
                'db_table': 'oktato',
            },
        ),
    ]
