# Generated by Django 2.2.19 on 2021-04-29 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_etradmin_hallgato_oktato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallgato',
            name='kepzes',
        ),
    ]
