# Generated by Django 2.2.19 on 2021-04-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_hallgato_kepzes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallgato',
            name='teljesitettkreditek',
        ),
    ]
