# Generated by Django 3.2 on 2021-05-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infosheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='cim',
            field=models.CharField(max_length=200),
        ),
    ]
