# Generated by Django 2.2.19 on 2021-04-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felvette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='felvette',
            name='teljesitette',
            field=models.IntegerField(default=0),
        ),
    ]
